In [3]:
import numpy as np

In [4]:
#1. Create a null array of size 10 but the fifth value which is 1

"""Here you created a list, but the syntax for array is similiar:
a = np.array([None] * 10, dtype=object)
It is good practice to specify the array's data type with the 'dtype' parameter. Since None can be anything, we use
dtype=object."""

a = np.array([None] * 10, dtype=object)
a = np.insert(a,4,[1])
print(a)

#a = ([None]) * 10
#a.insert(4, '1')
#print (a[:9])
"""The above prints the first 9 elements. Just print(a) if you want to print all 10 elements."""

[None None None None 1 None None None None None None]


'The above prints the first 9 elements. Just print(a) if you want to print all 10 elements.'

In [19]:
#2. Reverse a above created array (first element becomes last)
print(a[-1::-1])
"""In a notebook, the last instruction's output is always printed, so the above can be shorthanded into
a[-1::1]
"""

[None None None None None None 1 None None None None]


"In a notebook, the last instruction's output is always printed, so the above can be shorthanded into\na[-1::1]\n"

In [12]:
#3. Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np

pymat = [[0,1,2],[3,4,5],[6,7,8]]
npmat = np.array(pymat)
print ('numpy matrix is \n%s\n'%npmat)

numpy matrix is 
[[0 1 2]
 [3 4 5]
 [6 7 8]]



In [21]:
#4. Find indices of non-zero elements from [-2.3,-1,1,1,2,0,0,4,0]

lst = [-2.3,-1,1,1,2,0,0,4,0]
for n in lst:
    if (n < 0 or n > 0): #handles negative values now
        index = lst.index(n)
        print('The index of', n, "=", "[", index, "]")

The index of -2.3 = [ 0 ]
The index of -1 = [ 1 ]
The index of 1 = [ 2 ]
The index of 1 = [ 2 ]
The index of 2 = [ 4 ]
The index of 4 = [ 7 ]


In [22]:
#5. Create a 3x3x3 array with random values

#Using numpy.random.random
mat1 = np.random.random(size=(3,3))
print ('matrix generated from numpy.random.random is \n%s\n'%mat1)

matrix generated from numpy.random.random is 
[[0.40273968 0.65350252 0.42584359]
 [0.04916452 0.26944613 0.2000679 ]
 [0.03857851 0.27130224 0.10573283]]



In [24]:
#6. Create a 10x10 array with random values and find the minimum and maximum values

mat2 = np.random.randint(low=0,high=20,size=(10,10))
print ('matrix generated from numpy.random.random is \n%s\n'%mat2)
"""You forgot to find the min and max values:"""
print("min", mat2.min(), "max", mat2.max())
"""Note that this would be a useful test case of the function np.random.randint() to ensure that if you asked for
the range [0,20) you get only numbers in that range.""";

matrix generated from numpy.random.random is 
[[ 1  1 16  3  9  6  1 17 10 10]
 [ 1 16  3  5  7 11  4 19  6 10]
 [ 5 14  6  3 15 15 13 18  3  6]
 [ 6 18 12 12 18 17 19 18 16  4]
 [19  6 17  1 12 16  5  3  0 18]
 [16 10  1  3  4  8 17  1  2  9]
 [ 6 19  4  0  7  8  7  2 11  8]
 [10 11 10  8  9 10  6  4 12  2]
 [12  3  1 15  1 14 12 12  9 11]
 [ 0 10 16 11  9  9  4  6 10  3]]

min 0 max 19


In [25]:
#7. Create a random vector of size 30 and find the mean value

#Using numpy.random.random
vec1 = np.random.random(size=(30))
print ('matrix generated from numpy.random.random is \n%s\n'%vec1)
print ('Overall mean of vector is \n%s\n'%np.mean(vec1))

matrix generated from numpy.random.random is 
[0.10518838 0.04693611 0.66387581 0.73203968 0.53097648 0.51111559
 0.33781411 0.65152426 0.7165172  0.15093496 0.91288963 0.81042547
 0.70846951 0.12801277 0.57187289 0.53294225 0.95253395 0.33642315
 0.73268093 0.66825757 0.14303794 0.38265138 0.89444566 0.67197256
 0.36132685 0.50254162 0.98804981 0.38592636 0.79364122 0.8353539 ]

Overall mean of vector is 
0.5586792667324797



In [61]:
#8. Create a 2d array with 1 on the border and 0 inside
#**Question**: this works, but honestly I am not sure why. I don't understand how the slicing is happening in the 2D matrix
#The second "1:4" appears to control the what happens. As long as ":" stays constant, I can see how the second piece controls what's going on. I think I don't know what the first ":" is doing, exactly.
array1 = np.zeros((5,4))
array1[0] = 1 #set first row to 1
array1[-1] = 1 #set last row to 1
array1[:, 0] = 1 #set first col to 1
array1[:, -1] = 1 #set last col to 1
print("Jill's:\n", array1)

"""Now for the problem itself: we can generate an m x n matrix with zeros, then set the first row to 1, last row to 1,
first column to 1, and last column to 1. This will give us the full border of ones."""

def border_array(m, n):
    """Returns an m x n matrix with a border of 1 and interior of 0."""
    a = np.zeros((m, n))
    # Set first row to 1. We could use a[0, :] = 1, but we can use the shortcut!
    a[0] = 1
    # Set last row to 1. We don't even need to refer to the size 'n' here if we utilize negative indexing.
    a[-1] = 1
    # Set first column to 1. Note that a[0, 0] is already 1, but we override it with 1 so it's OK.
    a[:, 0] = 1
    # Set last column to 1. Note that a[-1, -1] is already 1, but we override it with 1 so it's OK.
    a[:, -1] = 1
    return a

print("Using border_array():")
print(border_array(5, 4))

Jill's:
 [[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]
Using border_array():
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [57]:
z = ([1,2,3,4,5])
print(z[-1:])



[5]


In [320]:
#9. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

mat53 = np.random.random(size=(5,3))
mat32 = np.random.random(size=(3,2))
print ("mat1=", mat53)
print ("mat2=",mat32)
product = np.dot(mat53, mat32)
print("product=", product)



mat1= [[0.94604661 0.83414915 0.4491943 ]
 [0.4337302  0.55981213 0.39858667]
 [0.20202951 0.55990693 0.31369956]
 [0.8143894  0.77542236 0.44637564]
 [0.52406032 0.63097701 0.94516279]]
mat2= [[0.79855583 0.54538824]
 [0.66005971 0.10754943]
 [0.73363607 0.1704974 ]]
product= [[1.63560442 0.68226142]
 [1.00828477 0.36471682]
 [0.76104516 0.22388715]
 [1.48963773 0.60366052]
 [1.52837944 0.51482535]]


In [12]:
#10. Extract the integer part of a random array

"""Question: not exactly sure what to do here? See Week 1 Solutions document below"""

array_b = np.random.randn(10) #generate random normal distribution; extract only integers from each value; i'm sure there is a more efficient way :-)
"""print ("\n","***Is this what you were thinking?***","\n")
print ("Here's the array:", array_b)
for digit in array_b:
    digit_s = str(digit) #turn each float in array_b into a string
    for i in digit_s: #iterate across each string to get each integer value
        if i.isdigit():
            print("I am an integer =",i)
   
https://numpy.org/doc/stable/reference/generated/numpy.trunc.html

Scroll 
"""

truncated_arr = np.trunc(array_b)
print ("array is truncated:",truncated_arr)

"""Let's make it more interesting by scaling b up."""
scaled_arr = 10 * array_b
print("c=", c)
print("trunc_c=",np.trunc(c))


array is truncated: [-0.  0.  0. -0.  0. -0. -0. -0. -0. -0.]
c= [-22.84629125   9.01996974  -4.71934215  16.01688599   7.06540888
  11.08453672  -6.76150993  19.58166658   6.99569369   6.22685157]
trunc_c= [-22.   9.  -4.  16.   7.  11.  -6.  19.   6.   6.]


In [21]:
#11. Create a 5x5 matrix with row values ranging from 0 to 4

mat5x5 = np.zeros((5,5)) # create a 5x5 matrix of zeros to start
#mat5x5 += np.arange(5)#I was struggling and found this code online and it works. I think what it's doing is that for each row in mat5x5, iterate and populate each row of `mat5x5` with 0 - 4 print(mat55); start at 0, max 5, step 1
for row in mat5x5: #Question: I created this for loop, thinking it would do the same as above, but it seems to create a set of arrays vs a matrix; so, I am a bit confused.
    mat5x5 = np.arange(5)
    """There is a bug here - you meant row = np.arange(5). This sets the whole matrix to a 1D array."""
    print("mat5x5=",mat5x5, "type=",type(mat5x5), "size=",mat5x5.size)
#print(mat5x5, type(mat5x5)) 

"""So the result is actually 1D array:"""
print("Final matrix:")
print(mat5x5)

"""The correct function is tile(): https://numpy.org/doc/stable/reference/generated/numpy.tile.html
We create the range as you did, and then tile it in the second dimension. I never know whether it should be (1, 5)
or (5, 1) in tiling so I try both and see which is right. :)"""
print(np.tile(np.arange(5), (5, 1))) #numpy.tile(Array, reps = [row-repeats], [col-repeats]); this says create an array from 0-4 and repeat¶

mat5x5= [0 1 2 3 4] type= <class 'numpy.ndarray'> size= 5
mat5x5= [0 1 2 3 4] type= <class 'numpy.ndarray'> size= 5
mat5x5= [0 1 2 3 4] type= <class 'numpy.ndarray'> size= 5
mat5x5= [0 1 2 3 4] type= <class 'numpy.ndarray'> size= 5
mat5x5= [0 1 2 3 4] type= <class 'numpy.ndarray'> size= 5
Final matrix:
[0 1 2 3 4]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [552]:
#12.  Create a random vector of size 10 and sort it

random_vec = np.random.random(size=(10))
print ("original:", random_vec)
np.sort(random_vec)
print ("sorted:", random_vec)

original: [0.53995558 0.73393044 0.11538771 0.28050683 0.54481254 0.1172875
 0.75315917 0.73346305 0.06280361 0.55951623]
sorted: [0.53995558 0.73393044 0.11538771 0.28050683 0.54481254 0.1172875
 0.75315917 0.73346305 0.06280361 0.55951623]


In [234]:
#13. Consider two random array A anb B, check if they are equal

A = np.random.randint(5, size = 10)
B = np.random.randint(5, size = 10)
#A = np.random.randint(1, size = 10) #case is equal
#B = np.random.randint(1, size = 10)
print("A=", A)
print("B=", B)
test_equality = A == B
if False in test_equality:
    print(A, "is not equal to", B)
else:
    print(A, "is equal to", B)

A= [3 4 1 2 1 2 2 3 3 0]
B= [4 3 1 4 4 4 4 4 4 0]
[3 4 1 2 1 2 2 3 3 0] is not equal to [4 3 1 4 4 4 4 4 4 0]


In [49]:
#14. How to tell if a given 2D array has null columns?

#*Note: I figured out how to tell if an array is dimension is empty, but then I realized that wasn't the question
#pymat2 = [[0,1,2],[]] 
#npmat2 = np.array(pymat2) #create 2D  matrix with NULL column
#for col in npmat2: #iterate on matrix
    #print(col)
    #if len(col) == 0: #check length of columns in matrix
        #print("Column", col, "is NULL") 

#There must be a simpler way, and not even sure this is correct. I am used to dealing with strings vs numbers.
#I think this gets at the general idea. I feel like you showed a simple way to do this, but I cant' find it in the video.
#I know this is totally "hacky"

pymat3 = [[None,1,None],[1,2,None]] #create a 2D array with Null columns
npmat3 = np.array(pymat3)
print (npmat3)
for col in range(npmat3.shape[0]): #iterate on all columns; I found this code, and .shape[0] or .shape[1] seems to work and not sure why
    x = str(npmat3[:,col])
    if "None" in x:
        print("Column", col, "is NULL:",npmat3[:,col]) 

"""As a general rule in python, and in particular numpy, loops are a lot slower (and harder to read) than array
operations. Numpy is optimized to do operations on entire rows or columns a lot faster than looping over elements.
Here we use a variant of all() provided by numpy: np.all() can work along a dimension, while all() is a generic
python function that works on any generator. For each column, we use np.all() to find if it's [i.e., a specific column(s)] all nulls; then we
use np.where() to find the columns that tested positive. Both np.all() and np.where() are block operations instead
of loops so fast and easy to read.
"""

"""Prints the indices of all null columns. Remember that np.where() returns a tuple of size 1 on a 1D array, so
we take the first element in the tuple. See

https://numpy.org/doc/stable/reference/generated/numpy.where.html"""
print(np.all(npmat3 == None, axis=0)[0]) #I think the last [0] is specifying the column you want to look at
print("Column that tests positive for NULL:",np.where(np.all(npmat3 == None, axis=0))[0])

[[None 1 None]
 [1 2 None]]
Column 0 is NULL: [None 1]
True
Column that tests positive for NULL: [2]


In [57]:
#15. Considering a four dimensions array, how to get sum over the last two axis at once?

#arrayx4 = np.random.randn(3,4) #make 4-dim array (matrix)
#slice = arrayx4[1:3] #slice out rows 1 & 2
#sum = np.sum(slice) #**Question**:this should sum across all values in the two rows. I think this is what you are asking for "all at once"?
#print ("matrix=\n",arrayx4, "\n","slice=\n", slice, "\n", "sum=\n",sum)


"""Above you actually created a 2D array of size 3 x 4. To create a 4D array you need to pass in a size which is 
a tuple of length 4."""

tensor = np.random.randn(3,4,5,6)
print(tensor.shape)
"""np.sum() can take multiple axes, here the last two are 2, 3 (remember everything is 0-based). Since we are summing
over the last 2 dimensions, our sum result should be a 3 x 4 matrix, not a scalar. Indeed:"""
print(np.sum(tensor, axis=(2,3)))

matrix=
 [[ 1.59105567 -0.68658579  0.57775759 -1.33714196]
 [ 0.77469506  0.36794857  0.77842878 -1.74303701]
 [-1.26136676 -1.20059614  0.97703133 -0.70505785]] 
 slice=
 [[ 0.77469506  0.36794857  0.77842878 -1.74303701]
 [-1.26136676 -1.20059614  0.97703133 -0.70505785]] 
 sum=
 -2.011954023152269
(3, 4, 5, 6)
[[-2.68486963  4.67002836 -3.26730296  1.58474434]
 [-0.71271086 11.58244163 -4.42011975  1.81388055]
 [ 4.18223714 -5.57458232  5.735653    6.07050463]]


In [639]:
#16. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
#Question: I'm not sure if this is right. I tried different things, but taking the outer product of
#arrays with non-equal dimensions seems to work. I did not find a solution in the videos or in the notebook, so
#I tried to find something online.

arrayx553 = np.random.randn(5,5,3)
arrayx55 = np.random.randn(5,5)
product2 = np.outer(arrayx553,arrayx55)

print("PRODUCT=", product2)


PRODUCT= [[-0.55683069 -0.10913743  0.35009651 ...  0.10639027 -0.63385807
  -0.43362835]
 [ 0.7131353   0.13977275 -0.44837001 ... -0.13625445  0.81178458
   0.55534957]
 [ 0.69536258  0.13628934 -0.43719576 ... -0.13285872  0.79155333
   0.54150918]
 ...
 [ 0.09396184  0.01841629 -0.05907669 ... -0.01795272  0.10695975
   0.07317219]
 [ 0.73653001  0.14435806 -0.46307898 ... -0.14072433  0.83841552
   0.57356805]
 [-0.19673646 -0.03855986  0.12369424 ...  0.03758925 -0.22395137
  -0.15320726]]


In [646]:
#17. Extract all the contiguous 3x3 blocks from a random 10x10 matrix
#CONFUSED: Outside of my understanding from the lectures. Sorry. I can make the matrix but not sure how 
#to get the 'blocks'

rand10x10 = np.random.rand(10,10)

#***SEE WEEK ONE SOLUTIONS***

print(rand10x10)

[[0.28299038 0.92929508 0.5819256  0.85359676 0.30946377 0.31539238
  0.18808261 0.93542594 0.53330836 0.98846045]
 [0.17151214 0.85999446 0.87649188 0.03301212 0.29433147 0.78470413
  0.26142262 0.37223081 0.30017491 0.03787479]
 [0.30143893 0.11405732 0.41309749 0.24767977 0.28628935 0.72314224
  0.04785718 0.97017102 0.28172699 0.48872285]
 [0.40079194 0.82709528 0.01296963 0.14253996 0.92453485 0.1474351
  0.09029745 0.54191641 0.43812169 0.8730783 ]
 [0.499087   0.37192868 0.49104418 0.60618073 0.89990439 0.54796489
  0.0534385  0.78879843 0.9362946  0.52129459]
 [0.71068512 0.75658896 0.25781767 0.11359578 0.40528264 0.63122027
  0.38923976 0.77104648 0.33306476 0.05145946]
 [0.01701032 0.14899041 0.79534657 0.73492336 0.74300566 0.50672295
  0.02260824 0.431547   0.77351026 0.52391162]
 [0.55794677 0.88295655 0.97337668 0.75026986 0.87466479 0.12338406
  0.86215308 0.70451296 0.90886975 0.55105275]
 [0.9702921  0.83527949 0.31413415 0.50112805 0.41037044 0.72356891
  0.6945783  

In [74]:
#18. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?
#UPDATED

def contiguous_4x4_blocks(a):
    # a.shape is a tuple, and we can extract its values into two variables m, n with one line instead of
    # m = a.shape[0]
    # n = a.shape[1]
    m, n = a.shape
    #print("m=",m,"n=",n)
    #print(range(m-4),range(n-4) )
    return [a[i:i+4, j:j+4] for i in range(m-4) for j in range(n-4)]

"""Let's test this but not on a random matrix so it's easy for us to verify this by eye."""

a = np.arange(256).reshape(16,16)
print(a)
for block in contiguous_4x4_blocks(a):
    print("block=\n",block)
    print ('Overall sum of block is %s\n'%np.sum(block))

[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
 [ 16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31]
 [ 32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47]
 [ 48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63]
 [ 64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95]
 [ 96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111]
 [112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127]
 [128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143]
 [144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175]
 [176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191]
 [192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207]
 [208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223]
 [224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 

In [654]:
#19. Generate 2 random gaussian distributions and run a t-test to see differences

from scipy import stats

a = np.random.normal(0,1,100)
b = np.random.normal(1,1,10)
#print(a)
#print(b)
print(stats.ttest_ind(a,b))

"""Returns the statistic and p-value, see
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html""";

[ 4.29998447e-01 -8.76584729e-01 -2.29376268e-01 -8.33961473e-01
  8.10687218e-01  4.03639015e-01 -5.30062443e-01  3.21491552e-01
  3.50682325e-01 -1.29275397e-01  3.90015444e-01 -1.85215039e-01
  4.19108675e-01 -2.01764080e-01  1.13751547e+00  5.22797879e-01
  4.50104134e-01 -3.74705002e-01 -1.57021728e+00  1.02023372e+00
 -7.54699553e-01  9.87569189e-01  4.05805975e-01  1.61531044e+00
  2.33409382e-01 -9.17963433e-01  1.06011066e+00  2.06184046e-03
  2.77355487e-01 -1.98090170e-01  4.88405977e-01  2.00612909e+00
  8.33015398e-01  2.64873845e-01 -1.64722551e-01 -7.22530845e-02
 -1.35303436e+00 -9.20683079e-01 -1.54672785e+00 -8.16378882e-01
 -5.63272877e-01  1.25475297e+00 -2.53928049e-01  5.07977856e-01
 -1.03777843e+00  4.46801056e-01  9.06032625e-01 -5.38869818e-01
  1.05338072e-01 -8.34322724e-01  7.49290357e-01 -6.61950654e-02
 -6.16857400e-01 -1.26655329e+00 -6.04125350e-02  1.76674812e+00
 -4.02691092e-01 -1.97625440e-03 -1.91733715e-01 -1.43649717e+00
  6.52579356e-02 -1.31233

Ttest_indResult(statistic=-3.56241458394408, pvalue=0.000548247087356847)