In [19]:
"""In Python, we can use the # sign for a line comment (everything after the # sign on that line will be ignored).
A block comment starts and ends with three quote signs. We use those for function and file documentation. Here I am
using block comments to denote my comments on your exercises since the notebook colors them in red, which is
convenient."""

"""Place all imports at the beginning of a notebook/script/file. I also sort them in alphabetical order."""
import numpy as np

In [13]:
#1. Create a null array of size 10 but the fifth value which is 1
"""Here you created a list, but the syntax for array is similiar:

a = np.array([None] * 10, dtype=object)

It is good practice to specify the array's data type with the 'dtype' parameter. Since None can be anything, we use
dtype=object."""
a = ([None]) * 10
a.insert(4, '1')
print (a[:9])
"""The above prints the first 9 elements. Just print(a) if you want to print all 10 elements."""

[None, None, None, None, '1', None, None, None, None]


'The above prints the first 9 elements. Just print(a) if you want to print all 10 elements.'

In [14]:
#2. Reverse a above created array (first element becomes last)
print(a[-1::-1])
"""In a notebook, the last instruction's output is always printed, so the above can be shorthanded into
a[-1::1]
"""

[None, None, None, None, None, None, '1', None, None, None, None]


"In a notebook, the last instruction's output is always printed, so the above can be shorthanded into\na[-1::1]\n"

In [15]:
#3. Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np

pymat = [[0,1,2],[3,4,5],[6,7,8]]
npmat = np.array(pymat)
print ('numpy matrix is \n%s\n'%npmat)

numpy matrix is 
[[0 1 2]
 [3 4 5]
 [6 7 8]]



In [34]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]

list = [1,2,0,0,4,0]
for n in list:
    if n > 0:
        index = list.index(n)
        print('The index of', n, "=", "[", index, "]")
        
"""The above code has several issues:
- Don't use the reserved word 'list' for a variable; it can be confusing. Call it 'lst', 'data', etc.
- Bug 1: it only finds positive elements, not all non-zeros (which could be negative as well!).
- Bug 2: it won't give the expected result if there is a repeated non-zero element in the list. index() returns
the first occurrence of a value. If the last element were also 4, we would not return it.
- Slow performance: if the list is of size n, we first need n operations to find all values in the list.
('for n in list'). Thus, the loop is executed at worst n times (when all values are non-zero). Furthermore, every
call list.index() has to potentially search through the entire list to find the value
(take the list = [1,2,3,4,...,n]; value i will require i times to find the value 'i', and for large i ~ n we need
to loop over [nearly] the whole list. The total number of passes over elements is 1+2+3+4+...+n = n(n-1)/2. For large
n, this is about n^2, so the code will take 4 times longer to run over a twice larger list. We should be able to
do faster than that, since the total amount of data in our problem is n. For very large n, n^2 is a lot larger than
n.

Instead, we can use the function programming tools to filter the list (finding elements that match a certain criteria
should trigger in our minds the use of filter(). But we want the index, not the element itself, which calls for 
another tool we haven't learned yet: enumerate(). 

enumerate(a) is a generator that returns the tuples (0, a[0]), (1, a[1]), (2, a[2]), ..., (n-1, a[n-1]) where n=len(a).
This gives us an index and value together, so we can do this:
"""

# First, fix the symbol overriding above. Otherwise, we can't use the list keyword below to read items from 
# a generator exprssion, since it was used above for a variable.
del list

def non_zero_indices(data):
    """Returns the list of all non-zero elements in the list 'data'. Actually, 'data' can be any iterable of numbers:
    numpy array, or a generator expression of numbers. This code runs in O(n) time and O(1) storage for a list of
    n elements."""
    # Returning the actual list. We could keep the returned value as a generator expression for more efficient
    # code if it is to be fed into downstream code.
    # Let's parse this:
    # enumerate(data) gives us (0, data[0]), (1, data[1])
    # filter() takes a function of a tuple (called t). We return True if and only if t[1], the data element, is
    # non-zero. This will give us a generator of all tuples (i, data[i]) where data[i] > 0.
    # Now, we apply a map to each tuple - return the first element in the tuple, i, which is the index of the element.
    # Finally, we read all elements from the generator into a list. Note that our code is not just shorter but
    # also more efficient as it touches each element in the array once, so for n elements it runs in time ~ n.
    return list(map(lambda t: t[0], filter(lambda t: t[1] != 0, enumerate(data))))

def non_zero_indices_using_index(data):
    """This is your code, just wrapped in a function. This accepts only a list, not a numpy array, since we're
    using index() which is a list function. This runs in O(n^2) time for an n-element list."""
    index_list = []
    for n in data:
        if n > 0:
            index = data.index(n)
            # Say we add it to a list instead of printing it so we can compare both implementations.
            index_list.append(index)
    return index_list

# For the above test case, both implementations work.
data = [1, 2, 0, 0, 4, 0]   # Space after each comma is a style guide.
print("Only non-negative values, each one occuring once")
print(non_zero_indices(data))
print(non_zero_indices_using_index(data))

# Repeated values work only with the map-filter implementation.
print("Repeated values")
data = [1, 2, 0, 0, 4, 4]
print(non_zero_indices(data))
print(non_zero_indices_using_index(data))

# Negative values work only with the map-filter implementation.
print("Negative values")
data = [-1, 2, 0, 0, 4, 0]
print(non_zero_indices(data))
print(non_zero_indices_using_index(data))

# Compare timing on a large list with a large spread of values, which is where non_zero_indices_using_index() will
# take the longest to find elements. On my machine, I see a 100x speedup!
data = list(np.random.randint(low=-10000, high=10000, size=10000))
%timeit non_zero_indices(data)
%timeit non_zero_indices_using_index(data)

"""In summary, we see a typical code development: we start with a simple function, then find better ways to implement
it. We write tests against different types of inputs to verify the code's correctness. Finally, we benchmark our code
and figure out if there are bottlenecks and how to make it faster for large problems. We make sure to document each
method, saying what it takes as input, what it outputs, and how fast it runs. As you can see, even the simplest
tasks can be drastically improved."""; # This little ; at the end is there just so that the notebook doesn't print this comment.

The index of 1 = [ 0 ]
The index of 2 = [ 1 ]
The index of 4 = [ 4 ]
Only non-negative values, each one occuring once
[0, 1, 4]
[0, 1, 4]
Repeated values
[0, 1, 4, 5]
[0, 1, 4, 4]
Negative values
[0, 1, 4]
[1, 4]
3.25 ms ± 60 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
401 ms ± 772 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [37]:
"""Follow-up on the previous cell: if you're using numpy arrays instead of lists, numpy already has a shortcut for
doing what we did:"""

data = np.array([-1, 2, 0, 0, 4, 0])
"""np.where() returns a tuple of indices for each dimension of the array that match the expression data != 0.
Since this is a 1D array, it's a tuple of size 1, so we typically use np.where(data != 0)[0] as our answer."""
np.where(data != 0)[0]

array([0, 1, 4])

In [17]:
#5. Create a 3x3x3 array with random values

#Using numpy.random.random
mat1 = np.random.random(size=(3,3))
print ('matrix generated from numpy.random.random is \n%s\n'%mat1)

matrix generated from numpy.random.random is 
[[0.68208693 0.9277571  0.01802716]
 [0.77010355 0.43851083 0.13145025]
 [0.19917503 0.97919282 0.40063113]]



In [41]:
#6. Create a 10x10 array with random values and find the minimum and maximum values

mat2 = np.random.randint(low=0,high=20,size=(10,10))
print ('matrix generated from numpy.random.random is \n%s\n'%mat2)

"""You forgot to find the min and max values:"""
print("min", mat2.min(), "max", mat2.max())
"""Note that this would be a useful test case of the function np.random.randint() to ensure that if you asked for
the range [0,20) you get only numbers in that range.""";

matrix generated from numpy.random.random is 
[[ 4  8 18 13 10  9 13  0  6 17]
 [ 8  0  9  9  8 10 16 10  8 11]
 [12  2  3  0 15 16 10 19 13  6]
 [ 7 14 18  1  5  8  9 13  6  5]
 [12 12  3  3 17  2 14  2 13  5]
 [ 2  9 13 16 19  9 19 14 15 10]
 [19 16 15 14  8  7 15 10  1 13]
 [ 0 10  4  2  1 18  5  5  7  5]
 [16 12  9 19 13 19  6 13 13  0]
 [ 4 16 17 16  6 11  8  7  8 17]]

min 0 max 19


In [20]:
#7. Create a random vector of size 30 and find the mean value

#Using numpy.random.random
vec1 = np.random.random(size=(30))
print ('matrix generated from numpy.random.random is \n%s\n'%vec1)
print ('Overall mean of vector is \n%s\n'%np.mean(vec1))

matrix generated from numpy.random.random is 
[0.78377484 0.71798643 0.89393805 0.46867435 0.72821659 0.03454968
 0.31198322 0.61716664 0.57931898 0.3315161  0.40624549 0.27103195
 0.12632674 0.2781223  0.84456975 0.71218764 0.87216624 0.43054051
 0.79736251 0.00698133 0.59892498 0.0351275  0.37707422 0.58333232
 0.48889496 0.92291963 0.80933515 0.63599263 0.82042715 0.31335971]

Overall mean of vector is 
0.526601587275102



In [13]:
#8. Create a 2d array with 1 on the border and 0 inside
#**Question**: this works, but honestly I am not sure why. I don't understand how the slicing is happening in the 2D matrix
#The second "1:4" appears to control the what happens. As long as ":" stays constant, I can see how the second piece controls what's going on. I think I don't know what the first ":" is doing, exactly.
array1 = np.ones((2,5))
array1[:,1:4 ] = 0
print(array1)

"""To understand slicing, just keep in mind that : means the entire range of a dimension. Hence, for a 2D array a,

a[1:4, :] = the second, third and fourth rows of a (since we specified : in the second dimension = columns)
a[:, 1:4] = the second, third and fourth columns of a (since we specified : in the first dimension = columns)
a[:, :] = all of a
a[1:4, 2:3] = the sub-matrix of a starting at a[1,1] and ending at a[3,2] (row range + column range).

In numpy, they added a shortcut/convenience that may be confusing you at the moment -- if you want to slice in the
first dimension only (i.e., get a row range), you can omit the second : . Thus

a[1:4] is the same as a[1:4, :]

If it's confusing, just use the full notation a[1:4, :].

To answer your question above, the first : controls the row range, which means get all rows, while the second
range (say, 1:4) controls the column range. Thus a[:, 1:4] returns the second, third and fourth columns. In your
function you are only setting the left and right borders to 1. I interpreted the question as having border of 1 all
around.

Now for the problem itself: we can generate an m x n matrix with zeros, then set the first row to 1, last row to 1,
first column to 1, and last column to 1. This will give us the full border of ones.
"""

def border_array(m, n):
    """Returns an m x n matrix with a border of 1 and interior of 0."""
    a = np.zeros((m, n))
    # Set first row to 1. We could use a[0, :] = 1, but we can use the shortcut!
    a[0] = 1
    # Set last row to 1. We don't even need to refer to the size 'n' here if we utilize negative indexing.
    a[-1] = 1
    # Set first column to 1. Note that a[0, 0] is already 1, but we override it with 1 so it's OK.
    a[:, 0] = 1
    # Set last column to 1. Note that a[-1, -1] is already 1, but we override it with 1 so it's OK.
    a[:, -1] = 1
    return a

print("Using border_array():")
print(border_array(5, 4))

NameError: name 'np' is not defined

In [158]:
z = ([1,2,3,4,5])
print(z[-1:])



[5]


In [320]:
#9. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

mat53 = np.random.random(size=(5,3))
mat32 = np.random.random(size=(3,2))
print ("mat1=", mat53)
print ("mat2=",mat32)
product = np.dot(mat53, mat32)
print("product=", product)



mat1= [[0.94604661 0.83414915 0.4491943 ]
 [0.4337302  0.55981213 0.39858667]
 [0.20202951 0.55990693 0.31369956]
 [0.8143894  0.77542236 0.44637564]
 [0.52406032 0.63097701 0.94516279]]
mat2= [[0.79855583 0.54538824]
 [0.66005971 0.10754943]
 [0.73363607 0.1704974 ]]
product= [[1.63560442 0.68226142]
 [1.00828477 0.36471682]
 [0.76104516 0.22388715]
 [1.48963773 0.60366052]
 [1.52837944 0.51482535]]


In [23]:
#10. Extract the integer part of a random array

#Question: not exactly sure what to do here? 

array_b = np.random.randn(10) #generate random normal distribution; extract only integers from each value; i'm sure there is a more efficient way :-)
#print ("\n","***Is this what you were thinking?***","\n")
print ("Here's the array:", array_b)
for digit in array_b:
    digit_s = str(digit)
    for i in digit_s:
        if i.isdigit():
            pass
            """An empty statement in python; you must have one inside a nested block or it will get confused
            about what to do with an empty block following an 'if'."""
            """I commented out your prints so we can see the results of the code below without scrolling down."""
            #print("I am an integer =",i)

"""You were in the right direction, but above we need to convert every float to a string, then check if it's a
digit, etc. - we want to do everything in floating point and not involve strings (which are a lot slower).
Fortunately, numpy provides a magic function to do this:

https://numpy.org/doc/stable/reference/generated/numpy.trunc.html

Scroll 
"""
print(np.trunc(array_b))

"""Let's make it more interesting by scaling b up."""
c = 10 * array_b
print("c=", c)
print("trunc_c=",np.trunc(c))

"""If you didn't know about the numpy function (which I didn't either, I googled it as I do for everything in numpy),
we could alternatively use map() on the array, and in the lambda function do something like lambda x: math.trunc(x),
where math is the standard math library ('import math' would be required). Or we could write a function that truncates
a float by hand, but in any case, not use strings.""";

Here's the array: [-0.75558812  1.32485087 -0.14963281  0.15590073  0.53357055  0.22896972
 -0.68888289  0.15046437 -0.17063717 -1.53840586]
[-0.  1. -0.  0.  0.  0. -0.  0. -0. -1.]
c= [ -7.55588117  13.24850873  -1.49632807   1.55900731   5.33570549
   2.28969723  -6.88882894   1.50464368  -1.70637172 -15.38405856]
trunc_c= [ -7.  13.  -1.   1.   5.   2.  -6.   1.  -1. -15.]


In [60]:
#11. Create a 5x5 matrix with row values ranging from 0 to 4

mat5x5 = np.zeros((5,5)) # create a 5x5 matrix of zeros to start
#mat5x5 += np.arange(5)#I was struggling and found this code online and it works. I think what it's doing is that for each row in mat5x5, iterate and populate each row of `mat5x5` with 0 - 4 print(mat55); start at 0, max 5, step 1
for row in mat5x5: #Question: I created this for loop, thinking it would do the same as above, but it seems to create a set of arrays vs a matrix; so, I am a bit confused.
    mat5x5 = np.arange(5)
    """There is a bug here - you meant row = np.arange(5). This sets the whole matrix to a 1D array."""
    print(mat5x5, type(mat5x5), mat5x5.size)
#print(mat5x5, type(mat5x5)) 

"""So the result is actually 1D array:"""
print("Final matrix:")
print(mat5x5)

"""The correct function is tile(): https://numpy.org/doc/stable/reference/generated/numpy.tile.html
We create the range as you did, and then tile it in the second dimension. I never know whether it should be (1, 5)
or (5, 1) in tiling so I try both and see which is right. :)"""
print(np.tile(np.arange(5), (5, 1)))

[0 1 2 3 4] <class 'numpy.ndarray'> 5
[0 1 2 3 4] <class 'numpy.ndarray'> 5
[0 1 2 3 4] <class 'numpy.ndarray'> 5
[0 1 2 3 4] <class 'numpy.ndarray'> 5
[0 1 2 3 4] <class 'numpy.ndarray'> 5
Final matrix:
[0 1 2 3 4]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [552]:
#12.  Create a random vector of size 10 and sort it

random_vec = np.random.random(size=(10))
print ("original:", random_vec)
np.sort(random_vec)
print ("sorted:", random_vec)

original: [0.53995558 0.73393044 0.11538771 0.28050683 0.54481254 0.1172875
 0.75315917 0.73346305 0.06280361 0.55951623]
sorted: [0.53995558 0.73393044 0.11538771 0.28050683 0.54481254 0.1172875
 0.75315917 0.73346305 0.06280361 0.55951623]


In [67]:
#13. Consider two random array A anb B, check if they are equal

A = np.random.randint(5, size = 10)
B = np.random.randint(5, size = 10)
#A = np.random.randint(1, size = 10) #case is equal
#B = np.random.randint(1, size = 10)
print("A=", A)
print("B=", B)
test_equality = A == B
if False in test_equality:
    print(A, "is not equal to", B)
else:
    print(A, "is equal to", B)
    
"""Correct! Instead of checking if there's a False value in an array, python provides the function all()"""
print(A == B)
print("all result", all(A == B))  # Returns True iff all values in an array are True. Similarly, cf. the function any().
"""Or we could use the numpy function that does all this for us:
https://numpy.org/doc/stable/reference/generated/numpy.array_equal.html"""
print("A == B?", np.array_equal(A, B))
print("A == A?", np.array_equal(A, A))

"""Style comment: use lowercase letters for all variables including matrices - a, b and not A, B.""";

A= [2 3 1 4 4 3 1 4 3 0]
B= [3 1 3 0 0 3 3 1 2 3]
[2 3 1 4 4 3 1 4 3 0] is not equal to [3 1 3 0 0 3 3 1 2 3]
[False False False False False  True False False False False]
all result False
A == B? False
A == A? True


In [36]:
#14. How to tell if a given 2D array has null columns?

#*Note: I figured out how to tell if an array is dimension is empty, but then I realized that wasn't the question
#pymat2 = [[0,1,2],[]] 
#npmat2 = np.array(pymat2) #create 2D  matrix with NULL column
#for col in npmat2: #iterate on matrix
    #print(col)
    #if len(col) == 0: #check length of columns in matrix
        #print("Column", col, "is NULL") 

#There must be a simpler way, and not even sure this is correct. I am used to dealing with strings vs numbers.
#I think this gets at the general idea. I feel like you showed a simple way to do this, but I cant' find it in the video.
#I know this is totally "hacky"

pymat3 = [[0,None,2],[3,None,4]] #create a 2D array with Null columns
npmat3 = np.array(pymat3)
for col in range(npmat3.shape[0]): #iterate on all columns; I found this code, and .shape[0] or .shape[1] seems to work and not sure why
    x = str(npmat3[:,col])
    if "None" in x:
        print("Column", col, "is NULL:",npmat3[:,col]) 
        
"""As a general rule in python, and in particular numpy, loops are a lot slower (and harder to read) than array
operations. Numpy is optimized to do operations on entire rows or columns a lot faster than looping over elements.
Here we use a variant of all() provided by numpy: np.all() can work along a dimension, while all() is a generic
python function that works on any generator. For each column, we use np.all() to find if it's all nulls; then we
use np.where() to find the columns that tested positive. Both np.all() and np.where() are block operations instead
of loops so fast and easy to read.
"""

"""Prints the indices of all null columns. Remember that np.where() returns a tuple of size 1 on a 1D array, so
we take the first element in the tuple. See

https://numpy.org/doc/stable/reference/generated/numpy.where.html"""
print("Column that text positive for NULL:",np.where(np.all(npmat3 == None, axis=0))[0])

Column 1 is NULL: [None None]
Column that text positive for NULL: [1]


In [85]:
#15. Considering a four dimensions array, how to get sum over the last two axis at once?

arrayx4 = np.random.randn(3,4) #make 4-dim array (matrix)
slice = arrayx4[1:3] #slice out rows 1 & 2
sum = np.sum(slice) #**Question**:this should sum across all values in the two rows. I think this is what you are asking for "all at once"?
print ("matrix=",arrayx4, "\n","slice=", slice, "\n", "sum=",sum)


"""Above you actually created a 2D array of size 3 x 4. To create a 4D array you need to pass in a size which is 
a tuple of length 4."""

tensor = np.random.randn(3,4,5,6)
print(tensor.shape)
"""np.sum() can take multiple axes, here the last two are 2, 3 (remember everything is 0-based). Since we are summing
over the last 2 dimensions, our sum result should be a 3 x 4 matrix, not a scalar. Indeed:"""
print(np.sum(tensor, axis=(2, 3)))

matrix= [[ 0.18546845  1.35982131 -2.21873518 -0.05207876]
 [ 0.94251265  0.93575419  1.67977604 -1.74821217]
 [-1.30990468 -0.4488677   1.50490394 -0.44999352]] 
 slice= [[ 0.94251265  0.93575419  1.67977604 -1.74821217]
 [-1.30990468 -0.4488677   1.50490394 -0.44999352]] 
 sum= 1.1059687420372832
(3, 4, 5, 6)
[[  4.54626235   6.63733306   3.7256565   -2.45235477]
 [  8.21551427   7.65729304  -2.38509093  -0.18550861]
 [-14.87626978  -0.71546403   1.10235407  10.04778306]]


In [639]:
#16. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
#Question: I'm not sure if this is right. I tried different things, but taking the outer product of
#arrays with non-equal dimensions seems to work. I did not find a solution in the videos or in the notebook, so
#I tried to find something online.

arrayx553 = np.random.randn(5,5,3)
arrayx55 = np.random.randn(5,5)
product2 = np.outer(arrayx553,arrayx55)

print("PRODUCT=", product2)

"""Yes, this one is out there, let's skip it. I think you did the right thing."""

PRODUCT= [[-0.55683069 -0.10913743  0.35009651 ...  0.10639027 -0.63385807
  -0.43362835]
 [ 0.7131353   0.13977275 -0.44837001 ... -0.13625445  0.81178458
   0.55534957]
 [ 0.69536258  0.13628934 -0.43719576 ... -0.13285872  0.79155333
   0.54150918]
 ...
 [ 0.09396184  0.01841629 -0.05907669 ... -0.01795272  0.10695975
   0.07317219]
 [ 0.73653001  0.14435806 -0.46307898 ... -0.14072433  0.83841552
   0.57356805]
 [-0.19673646 -0.03855986  0.12369424 ...  0.03758925 -0.22395137
  -0.15320726]]


In [46]:
#17. Extract all the contiguous 3x3 blocks from a random 10x10 matrix
#CONFUSED: Outside of my understanding from the lectures. Sorry. I can make the matrix but not sure how 
#to get the 'blocks'

rand10x10 = np.random.rand(10,10)

#print(rand10x10)

"""We can get each block by slicing operations. Suppose we have the 4x5 matrix (just an example)

 1  2  3  4  5
 6  7  8  9 10
11 12 13 14 15
16 17 18 19 20

then the first 3x3 block (top left corner) is

 1  2  3
 6  7  8
11 12 13

Then we take the next, overlapping block by shifting to the right by one column:

 2  3  4
 7  8  9
12 13 14

and so on until the end of the row. Now we can shift down by one row:

 6  7  8
11 12 13
16 17 18

and so on until we get to the bottom right corner:

 8  9 10
13 14 15
18 19 20

So each block starts at some index, (i, j), and ends at (i + 2, j + 2). So it is specified by

a[i:i+3, j:j+3]

Now, we want to make sure we include all possible (i, j)'s starting at the top left corner but not falling off the edge
of the array on the right or bottom. This ends up being:
"""

def contiguous_3x3_blocks(a):
    # a.shape is a tuple, and we can extract its values into two variables m, n with one line instead of
    # m = a.shape[0]
    # n = a.shape[1]
    m, n = a.shape
    #print("m=",m,"n=",n)
    #print(range(m-3),range(n-3) )
    return [a[i:i+3, j:j+3] for i in range(m-3) for j in range(n-3)]

"""Let's test this but not on a random matrix so it's easy for us to verify this by eye."""

a = np.arange(100).reshape(10,10)
print(a)
for block in contiguous_3x3_blocks(a):
    print(block)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
m= 10 n= 10
range(0, 7) range(0, 7)
[[ 0  1  2]
 [10 11 12]
 [20 21 22]]
[[ 1  2  3]
 [11 12 13]
 [21 22 23]]
[[ 2  3  4]
 [12 13 14]
 [22 23 24]]
[[ 3  4  5]
 [13 14 15]
 [23 24 25]]
[[ 4  5  6]
 [14 15 16]
 [24 25 26]]
[[ 5  6  7]
 [15 16 17]
 [25 26 27]]
[[ 6  7  8]
 [16 17 18]
 [26 27 28]]
[[10 11 12]
 [20 21 22]
 [30 31 32]]
[[11 12 13]
 [21 22 23]
 [31 32 33]]
[[12 13 14]
 [22 23 24]
 [32 33 34]]
[[13 14 15]
 [23 24 25]
 [33 34 35]]
[[14 15 16]
 [24 25 26]
 [34 35 36]]
[[15 16 17]
 [25 26 27]
 [35 36 37]]
[[16 17 18]
 [26 27 28]
 [36 37 38]]
[[20 21 22]
 [30 31 32]
 [40 41 42]]
[[21 22 23]
 [31 32 33]
 [41 42 43]]
[[22 23 24]
 [32 33 34]
 [42 43 44]]
[[23

In [ ]:
#18. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?
#This problem is outside of what I understand from the lectures. Sorry.

In [95]:
#19. Generate 2 random gaussian distributions and run a t-test to see differences

from scipy import stats

a = np.random.normal(0,1,100)
b = np.random.normal(1,1,10)
#print(a)
#print(b)
print(stats.ttest_ind(a,b))

"""Returns the statistic and p-value, see
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html""";

Ttest_indResult(statistic=-2.768737418594114, pvalue=0.0066245172598695485)
